### ISSUE TITLE
Error running db:findindexes

### ISSUE THREAD

**Issue by timvoet** [plentz/lol_dba#53]
```
Class: Dojo
Association type: has_many
Association options: {:through=>:disciplines}
Exception: undefined method `options' for nil:NilClass
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:131:in `block (2 levels) in check_for_indexes'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:90:in `each_pair'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:90:in `block in check_for_indexes'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:86:in `each'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:86:in `check_for_indexes'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/lol_dba.rb:177:in `simple_migration'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lol_dba-1.6.7/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/tvoet/.rbenv/versions/2.1.0/bin/rake:23:in `load'
/Users/tvoet/.rbenv/versions/2.1.0/bin/rake:23:in `<main>'
```

**Comment by plentz** [comment]
@timvoet what version of rails you're using? can you try with lol_dba 2.0.0 and paste here the error message? the version you're using was wrongly tagged in the souce code, so that line doesn't match the actual tagged source code.

**Comment by johnsonj** [comment]
I'm getting a similar error using lol_dba 2.0.0, rails 3.2.18, ruby 2.1.0. Happy to diagnose further. 

````
***************************
Class: EventDescription
Association type: has_many
Association options: {:through=>:events, :extend=>[]}
Exception: undefined method `options' for nil:NilClass
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:129:in `block (2 levels) in check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `each_pair'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `block in check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/lol_dba.rb:179:in `simple_migration'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/lol_dba-2.0.0/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.0/bin/rake:23:in `load'
/home/vagrant/.rvm/gems/ruby-2.1.0/bin/rake:23:in `<main>'
/home/vagrant/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>
````

**Comment by plentz** [comment]
@johnsonj can you send a PR or code snipped that breaks our tests with the same error? You just need to add the same kind of mapping that you have here https://github.com/plentz/lol_dba/tree/master/spec/fixtures

thanks in advance!

**Comment by plentz** [comment]
@timvoet @johnsonj sorry for taking so long. fixed :)

**Comment by johnsonj** [comment]
Thank you!
