### ISSUE TITLE
Error running  rake db:find_indexes

### ISSUE THREAD

**Issue by chaadow** [plentz/lol_dba#54]
```ruby
Class: Site
Association type: has_many
Association options: {:through=>:users, :extend=>[]}
Exception: undefined method `options' for nil:NilClass
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:129:in `block (2 levels) in check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `each_pair'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:92:in `block in check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:86:in `check_for_indexes'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/lol_dba.rb:179:in `simple_migration'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/lol_dba-2.0.0/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/vagrant/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.6/bin/rake:23:in `load'
/home/vagrant/.rvm/gems/ruby-2.1.6/bin/rake:23:in `<main>'
/home/vagrant/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chaadow** [comment]
Similar to #53 
Rails version : 3.2.21
lol_dba : 2.0.0

**Comment by chaadow** [comment]
It generated the migration to run eventually, but I got this error message along the way

**Comment by plentz** [comment]
@chaadow it's the same problem of #53 for sure, the difference is just that you're using the newest version. I'm closing it and you can keep an eye there, ok? :)
