### ISSUE TITLE
db:migrate_sql is broken for rails versions > 5

### ISSUE THREAD

**Issue by cmason** [plentz/lol_dba#94]
Running `db:migrate_sql` in versions of Rails > 5 results in this error:

```
$ rails db:migrate_sql
rails aborted!
NoMethodError: undefined method `migrations_path' for ActiveRecord::Migrator:Class
Did you mean?  migrations_path=
               migrations_paths
               migrations_paths=
/Users/cmason/.gem/ruby/2.5.0/gems/lol_dba-2.1.5/lib/lol_dba/sql_generator.rb:62:in `migrations'
/Users/cmason/.gem/ruby/2.5.0/gems/lol_dba-2.1.5/lib/lol_dba/sql_generator.rb:84:in `block in generate'
/Users/cmason/.gem/ruby/2.5.0/gems/lol_dba-2.1.5/lib/lol_dba/sql_generator.rb:53:in `generate_instead_of_executing'
/Users/cmason/.gem/ruby/2.5.0/gems/lol_dba-2.1.5/lib/lol_dba/sql_generator.rb:84:in `generate'
/Users/cmason/.gem/ruby/2.5.0/gems/lol_dba-2.1.5/lib/tasks/lol_dba.rake:12:in `block (2 levels) in <main>'
/Users/cmason/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/cmason/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/cmason/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/command.rb:48:in `invoke'
/Users/cmason/.gem/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
/Users/cmason/.gem/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
/Users/cmason/.gem/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
/Users/cmason/.gem/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cmason/.gem/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
/Users/cmason/.gem/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
/Users/cmason/.gem/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `block in require'
/Users/cmason/.gem/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/cmason/.gem/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => db:migrate_sql
(See full trace by running task with --trace)
```

**Comment by plentz** [comment]
closed by #95
