### ISSUE TITLE
Error is printed while executing db:find_indexes

### ISSUE THREAD

**Issue by gshopovski** [plentz/lol_dba#97]
Even if the error was printed, the task finished with error code 0.
```Class: User
Association type: has_many
Association options: {:through=>:downloads, :source=>:downloadable}
Exception: uninitialized constant User::Download
.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:152:in `compute_type'
.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/reflection.rb:350:in `compute_class'
.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/reflection.rb:346:in `klass'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:125:in `block (2 levels) in check_for_indexes'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:97:in `each_pair'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:97:in `block in check_for_indexes'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:91:in `each'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:91:in `check_for_indexes'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/lol_dba.rb:186:in `simple_migration'
.rvm/gems/ruby-2.3.0/gems/lol_dba-2.1.5/lib/tasks/lol_dba.rake:7:in `block (2 levels) in <top (required)>'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
.rvm/gems/ruby-2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
.rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<top (required)>'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `load'
.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `<top (required)>'
.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
bin/spring:15:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

**Comment by plentz** [comment]
thanks for reporting! can you post your models?

**Comment by plentz** [comment]
closing due to inactivity.
